name: pull tuya hourly to influxdb

on:
  schedule:
    - cron: '20 * * * *' # Run every hour at minute 20
  workflow_dispatch:  # Allow manual triggering

jobs:
  log-temperature:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure environment variables
      run: |
        cat > .env << EOF
        TUYA_ACCESS_ID=${{ secrets.TUYA_ACCESS_ID }}
        TUYA_ACCESS_SECRET=${{ secrets.TUYA_ACCESS_SECRET }}
        TUYA_DEVICE_ID=${{ secrets.TUYA_DEVICE_ID }}
        REGION=${{ secrets.REGION }}
        INFLUXDB_URL=${{ secrets.INFLUXDB_URL }}
        INFLUXDB_TOKEN=${{ secrets.INFLUXDB_TOKEN }}
        INFLUXDB_ORG=${{ secrets.INFLUXDB_ORG }}
        INFLUXDB_BUCKET=${{ secrets.INFLUXDB_BUCKET }}
        EOF

    - name: Run script
      run: python tuya_influx.py

    - name: Clean up
      run: rm -f .env
