name: pull tuya hourly to csv

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

permissions:
  contents: write
      
jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tuya/requirements.txt

    - name: Configure environment variables
      run: |
        cat > .env << EOF
        TUYA_ACCESS_ID=${{ secrets.TUYA_ACCESS_ID }}
        TUYA_ACCESS_SECRET=${{ secrets.TUYA_ACCESS_SECRET }}
        TUYA_DEVICE_ID=${{ secrets.TUYA_DEVICE_ID }}
        TUYA_BASE_URL=${{ secrets.TUYA_BASE_URL }}
        EOF
  
    - name: Run script
      run: python tuya/tuya_csv.py
        
    - name: Run script with append mode
      run: python tuya/tuya_csv.py --append
        
    - name: Commit processed files
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add *.csv
        git commit -m "Auto-commit processed data files" || echo "No changes to commit"
        git push

    - name: Clean up
      run: rm -f .env
