name: Tuya 5in1_temperature

on:
  schedule:
    # Run every hour at minute 20
    - cron: '20 * * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  log-temperature:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure environment variables
      run: |
        cat > .env 

    - name: Run temperature logger
      run: python tuya_influx.py

    - name: Clean up
      run: rm -f .env
